---
- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Restart nodeapp
  systemd:
    name: nodeapp
    state: restarted

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted
